spring:
  datasource:
    username: root
    password: "!Qtkddyd12"
    url: jdbc:mysql://localhost:3306/interfacedemo?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

